version: '2'
services:
  postgresql:
    image: scalingo/postgresql:10.4.0-1
    ports:
      - 5432:5432
    environment:
      DB_UID: 1000
    volumes:
      - ./docker/postgresql-data:/var/lib/postgresql:rw
    command: /postgresql
  mongo:
    image: scalingo/mongo:4.0.13-1
    volumes:
      - ./docker/mongodb-data:/var/lib/mongodb:rw
    environment:
      DB_UID: 1000
    command: /mongo
    ports:
      - "27017:27017"
  web:
    build: .
    volumes:
     - .:/usr/src/app:rw
    environment:
      PORT: 3000
      DEFAULT_FROM: "${DEFAULT_FROM}"
      DEFAULT_HOST: "${DEFAULT_HOST}"
      DISQUS_SHORTNAME: "${DISQUS_SHORTNAME}"
      FOG_PROVIDER: "${FOG_PROVIDER}"
      RECAPTCHA_SECRET_KEY: "${RECAPTCHA_SECRET_KEY}"
      RECAPTCHA_SITE_KEY: "${RECAPTCHA_SITE_KEY}"
      S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
      S3_KEY: "${S3_KEY}"
      S3_REGION: "${S3_REGION}"
      S3_SECRET: "${S3_SECRET}"
      RAILS_ENV: development
      MONGO_URL: "mongodb://admin:admin-secret@mongo:27017/strasbourgstartups-development?authSource=admin"
      DATABASE_URL: postgresql://admin:admin-secret@postgresql:5432/frenchtechstrasbourg_development
      DATABASE_URL_TEST: postgresql://admin:admin-secret@postgresql:5432/frenchtechstrasbourg_test
      WEBPACKER_DEV_SERVER_HOST: 172.17.0.1
    links:
      - postgresql
      - mongo
      - webpack
    ports:
      - 3000:3000
    command: bundle exec rails server -b 0.0.0.0 -p 3000
  webpack:
    build: .
    ports:
      - 3035:3035
    volumes:
      - ./:/usr/src/app
    command: bundle exec ./bin/webpack-dev-server
