development:
  # Configure available database clients. (required)
  clients:
    # Defines the default session. (required)
    default:
      uri: mongodb://heroku_app16726550:oj9l97cmnj0e0e41phldgjrbt4@ds033818.mongolab.com:33818/heroku_app16726550
test:
  clients:
    default:
      database: strasbourgstartups_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['APPSDECK_MONGO_URL'] %>
